[package]
name = "private_swap_compact"
version = "0.1.0"
edition = "2021"

[dependencies]
compact-runtime = { version = "0.1.0" }
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib", "rlib"]
